# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'test1' do
  pod 'SwiftSoup'
  pod 'Alamofire'
  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'GooglePlacesAutocomplete'
  pod 'GooglePlacePicker'
end
